#ifndef MODBUS_REGISTERS_H
#define MODBUS_REGISTERS_H

#define MODBUS_REG_PH                 0x0006
#define MODBUS_REG_SOIL_MOISTURE      0x0012
#define MODBUS_REG_SOIL_TEMPERATURE   0x0013
#define MODBUS_REG_SOIL_CONDUCTIVITY  0x0015
#define MODBUS_REG_SOIL_NITROGEN      0x001E
#define MODBUS_REG_SOIL_PHOSPHORUS    0x001F
#define MODBUS_REG_SOIL_POTASSIUM     0x0020
#define MODBUS_REG_DEVICE_ADDRESS     0x0100
#define MODBUS_REG_BAUD_RATE          0x0101

#endif // MODBUS_REGISTERS_H